import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import App from "@/components/App";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-sky-700 to-sky-900 h-screen flex flex-col items-center pt-100">
        <App />
      </main>
    </>
  );
}
